// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilkTea.Infrastructure.Persistence;

#nullable disable

namespace MilkTea.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124092815_RefactorToCleanArch")]
    partial class RefactorToCleanArch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MilkTea.Domain.Entities.Config.Definition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Code");

                    b.Property<int>("DefinitionGroupID")
                        .HasColumnType("int")
                        .HasColumnName("DefinitionGroupID");

                    b.Property<int>("IsEdit")
                        .HasColumnType("int")
                        .HasColumnName("IsEdit");

                    b.Property<int>("IsEncrypt")
                        .HasColumnType("int")
                        .HasColumnName("IsEncrypt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("Value");

                    b.Property<byte[]>("ValueImage")
                        .HasColumnType("longblob")
                        .HasColumnName("ValueImage");

                    b.HasKey("ID");

                    b.HasIndex("DefinitionGroupID");

                    b.ToTable("definition", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Config.DefinitionGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("definitiongroup", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Currency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.DinnerTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasColumnName("Code");

                    b.Property<byte[]>("EmptyPicture")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("EmptyPicture");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("Height");

                    b.Property<int?>("Longs")
                        .HasColumnType("int")
                        .HasColumnName("Longs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int")
                        .HasColumnName("NumberOfSeats");

                    b.Property<string>("Position")
                        .HasColumnType("longtext")
                        .HasColumnName("Position");

                    b.Property<int>("StatusOfDinnerTableID")
                        .HasColumnType("int")
                        .HasColumnName("StatusOfDinnerTableID");

                    b.Property<byte[]>("UsingPicture")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("UsingPicture");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("Width");

                    b.HasKey("ID");

                    b.HasIndex("StatusOfDinnerTableID");

                    b.ToTable("dinnertable", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.KindOfHotpot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("kindofhotpot", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasColumnName("Code");

                    b.Property<int>("MaterialsGroupID")
                        .HasColumnType("int")
                        .HasColumnName("MaterialsGroupID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int?>("StyleQuantity")
                        .HasColumnType("int")
                        .HasColumnName("StyleQuantity");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    b.Property<int?>("UnitID_Max")
                        .HasColumnType("int")
                        .HasColumnName("UnitID_Max");

                    b.HasKey("ID");

                    b.HasIndex("MaterialsGroupID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UnitID");

                    b.HasIndex("UnitID_Max");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.MaterialsGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("materialsgroup", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.MaterialsStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("materialsstatus", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<byte[]>("AvatarPicture")
                        .HasColumnType("longblob")
                        .HasColumnName("AvatarPicture");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Code");

                    b.Property<string>("Formula")
                        .HasColumnType("longtext")
                        .HasColumnName("Formula");

                    b.Property<int>("MenuGroupID")
                        .HasColumnType("int")
                        .HasColumnName("MenuGroupID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<bool?>("PrintSticker")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PrintSticker");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int?>("TasteQTy")
                        .HasColumnType("int")
                        .HasColumnName("TasteQTy");

                    b.Property<int>("UnitID")
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    b.HasKey("ID");

                    b.HasIndex("MenuGroupID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UnitID");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.MenuAndMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("MaterialsID")
                        .HasColumnType("int")
                        .HasColumnName("MaterialsID");

                    b.Property<int>("MenuID")
                        .HasColumnType("int")
                        .HasColumnName("MenuID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Quantity");

                    b.Property<int>("SizeID")
                        .HasColumnType("int")
                        .HasColumnName("SizeID");

                    b.HasKey("ID");

                    b.HasIndex("MaterialsID");

                    b.HasIndex("MenuID");

                    b.HasIndex("SizeID");

                    b.ToTable("menuandmaterials", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.MenuGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.ToTable("menugroup", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.MenuSize", b =>
                {
                    b.Property<int>("MenuID")
                        .HasColumnType("int")
                        .HasColumnName("MenuID");

                    b.Property<int>("SizeID")
                        .HasColumnType("int")
                        .HasColumnName("SizeID");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("CostPrice");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("SalePrice");

                    b.HasKey("MenuID", "SizeID");

                    b.HasIndex("SizeID");

                    b.ToTable("menu_size", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("ActionBy")
                        .HasColumnType("int")
                        .HasColumnName("ActionBy");

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ActionDate");

                    b.Property<int?>("AddNoteBy")
                        .HasColumnType("int")
                        .HasColumnName("AddNoteBy");

                    b.Property<DateTime?>("AddNoteDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AddNoteDate");

                    b.Property<string>("BillNo")
                        .HasColumnType("longtext")
                        .HasColumnName("BillNo");

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("int")
                        .HasColumnName("CancelledBy");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CancelledDate");

                    b.Property<int?>("ChangeBy")
                        .HasColumnType("int")
                        .HasColumnName("ChangeBy");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ChangeDate");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("DinnerTableID")
                        .HasColumnType("int")
                        .HasColumnName("DinnerTableID");

                    b.Property<int?>("MergedBy")
                        .HasColumnType("int")
                        .HasColumnName("MergedBy");

                    b.Property<DateTime?>("MergedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("MergedDate");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<int>("OrderBy")
                        .HasColumnType("int")
                        .HasColumnName("OrderBy");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("OrderDate");

                    b.Property<int?>("PaymentedBy")
                        .HasColumnType("int")
                        .HasColumnName("PaymentedBy");

                    b.Property<DateTime?>("PaymentedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PaymentedDate");

                    b.Property<decimal?>("PaymentedTotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PaymentedTotal");

                    b.Property<string>("PaymentedType")
                        .HasColumnType("longtext")
                        .HasColumnName("PaymentedType");

                    b.Property<decimal?>("PromotionAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PromotionAmount");

                    b.Property<int?>("PromotionID")
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    b.Property<int?>("PromotionPercent")
                        .HasColumnType("int")
                        .HasColumnName("PromotionPercent");

                    b.Property<int>("StatusOfOrderID")
                        .HasColumnType("int")
                        .HasColumnName("StatusOfOrderID");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("TotalAmount");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("DinnerTableID");

                    b.HasIndex("PromotionID");

                    b.HasIndex("StatusOfOrderID");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.OrdersDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("int")
                        .HasColumnName("CancelledBy");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CancelledDate");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<int?>("KindOfHotpot1ID")
                        .HasColumnType("int")
                        .HasColumnName("KindOfHotpot1ID");

                    b.Property<int?>("KindOfHotpot2ID")
                        .HasColumnType("int")
                        .HasColumnName("KindOfHotpot2ID");

                    b.Property<int>("MenuID")
                        .HasColumnType("int")
                        .HasColumnName("MenuID");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<int>("OrderID")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Price");

                    b.Property<int?>("PriceListID")
                        .HasColumnType("int")
                        .HasColumnName("PriceListID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<int>("SizeID")
                        .HasColumnType("int")
                        .HasColumnName("SizeID");

                    b.HasKey("ID");

                    b.HasIndex("KindOfHotpot1ID");

                    b.HasIndex("KindOfHotpot2ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("OrderID");

                    b.HasIndex("PriceListID");

                    b.HasIndex("SizeID");

                    b.ToTable("ordersdetail", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.PriceList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasColumnName("Code");

                    b.Property<int>("CurrencyID")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartDate");

                    b.Property<int>("StatusOfPriceListID")
                        .HasColumnType("int")
                        .HasColumnName("StatusOfPriceListID");

                    b.Property<DateTime>("StopDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StopDate");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("StatusOfPriceListID");

                    b.ToTable("pricelist", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.PriceListDetail", b =>
                {
                    b.Property<int>("PriceListID")
                        .HasColumnType("int")
                        .HasColumnName("PriceListID");

                    b.Property<int>("MenuID")
                        .HasColumnType("int")
                        .HasColumnName("MenuID");

                    b.Property<int>("SizeID")
                        .HasColumnType("int")
                        .HasColumnName("SizeID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Price");

                    b.HasKey("PriceListID", "MenuID", "SizeID");

                    b.HasIndex("MenuID");

                    b.HasIndex("SizeID");

                    b.ToTable("pricelistdetail", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.PromotionOnTotalBill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<decimal?>("ProAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ProAmount");

                    b.Property<int?>("ProPercent")
                        .HasColumnType("int")
                        .HasColumnName("ProPercent");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartDate");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<DateTime>("StopDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StopDate");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.ToTable("promotionontotalbill", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Size", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<int>("RankIndex")
                        .HasColumnType("int")
                        .HasColumnName("RankIndex");

                    b.HasKey("ID");

                    b.ToTable("size", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.StatusOfDinnerTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("statusofdinnertable", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.StatusOfOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("statusoforder", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.StatusOfPriceList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("statusofpricelist", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.StatusOfPromotion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("statusofpromotion", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Unit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Warehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<decimal>("AmountTotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("AmountTotal");

                    b.Property<int>("ImportFromSuppliersID")
                        .HasColumnType("int")
                        .HasColumnName("ImportFromSuppliersID");

                    b.Property<int>("MaterialsID")
                        .HasColumnType("int")
                        .HasColumnName("MaterialsID");

                    b.Property<decimal>("PriceImport")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PriceImport");

                    b.Property<decimal>("QuantityCurrent")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("QuantityCurrent");

                    b.Property<decimal>("QuantityImport")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("QuantityImport");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.HasKey("ID");

                    b.HasIndex("MaterialsID");

                    b.HasIndex("StatusID");

                    b.ToTable("warehouse", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.WarehouseRollback", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("OrderID")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<decimal>("QuantitySubtract")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("QuantitySubtract");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("warehouserollback", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("Address");

                    b.Property<string>("BankAccountName")
                        .HasColumnType("longtext")
                        .HasColumnName("Bank_AccountName");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("Bank_AccountNumber");

                    b.Property<string>("BankName")
                        .HasColumnType("longtext")
                        .HasColumnName("BankName");

                    b.Property<byte[]>("BankQRCode")
                        .HasColumnType("longblob")
                        .HasColumnName("Bank_QRCode");

                    b.Property<string>("BirthDay")
                        .HasColumnType("longtext")
                        .HasColumnName("BirthDay");

                    b.Property<DateTime?>("BreakTimeFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BreakTimeFrom");

                    b.Property<DateTime?>("BreakTimeTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BreakTimeTo");

                    b.Property<int?>("CalcSalaryByMinutes")
                        .HasColumnType("int")
                        .HasColumnName("CalcSalaryByMinutes");

                    b.Property<string>("CellPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("CellPhone");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasColumnName("Code");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<DateTime?>("EndWorkingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EndWorkingDate");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FullName");

                    b.Property<int>("GenderID")
                        .HasColumnType("int")
                        .HasColumnName("GenderID");

                    b.Property<string>("IdentityCode")
                        .HasColumnType("longtext")
                        .HasColumnName("IdentityCode");

                    b.Property<bool?>("IsBreakTime")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsBreakTime");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<int>("PositionID")
                        .HasColumnType("int")
                        .HasColumnName("PositionID");

                    b.Property<int?>("SalaryByHour")
                        .HasColumnType("int")
                        .HasColumnName("SalaryByHour");

                    b.Property<DateTime?>("ShiftFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ShiftFrom");

                    b.Property<DateTime?>("ShiftTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ShiftTo");

                    b.Property<DateTime?>("StartWorkingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartWorkingDate");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int>("TimekeepingOther")
                        .HasColumnType("int")
                        .HasColumnName("TimekeepingOther");

                    b.HasKey("ID");

                    b.HasIndex("GenderID");

                    b.HasIndex("PositionID");

                    b.HasIndex("StatusID");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Gender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("gender", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<int>("PermissionGroupID")
                        .HasColumnType("int")
                        .HasColumnName("PermissionGroupID");

                    b.HasKey("ID");

                    b.HasIndex("PermissionGroupID");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.PermissionDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    b.HasKey("ID");

                    b.HasIndex("PermissionID");

                    b.ToTable("permissiondetail", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.PermissionGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<int>("PermissionGroupTypeID")
                        .HasColumnType("int")
                        .HasColumnName("PermissionGroupTypeID");

                    b.HasKey("ID");

                    b.HasIndex("PermissionGroupTypeID");

                    b.ToTable("permissiongroup", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.PermissionGroupType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.HasKey("ID");

                    b.ToTable("permissiongrouptype", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("position", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ExpiryDate");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsRevoked");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refreshtokens", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.RoleDetail", b =>
                {
                    b.Property<int>("PermissionDetailID")
                        .HasColumnType("int")
                        .HasColumnName("PermissionDetailID");

                    b.Property<int>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.HasKey("PermissionDetailID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("roledetail", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("status", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("EmployeesID")
                        .HasColumnType("int")
                        .HasColumnName("EmployeesID");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<int?>("PasswordResetBy")
                        .HasColumnType("int")
                        .HasColumnName("Password_ResetBy");

                    b.Property<DateTime?>("PasswordResetDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Password_ResetDate");

                    b.Property<int>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int?>("StoppedBy")
                        .HasColumnType("int")
                        .HasColumnName("StoppedBy");

                    b.Property<DateTime?>("StoppedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StoppedDate");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UserName");

                    b.HasKey("ID");

                    b.HasIndex("EmployeesID")
                        .IsUnique();

                    b.HasIndex("StatusID");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.UserAndPermissionDetail", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("PermissionDetailID")
                        .HasColumnType("int")
                        .HasColumnName("PermissionDetailID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.HasKey("UserID", "PermissionDetailID");

                    b.HasIndex("PermissionDetailID");

                    b.ToTable("userandpermissiondetail", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.UserAndRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("userandrole", (string)null);
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Config.Definition", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Config.DefinitionGroup", "DefinitionGroup")
                        .WithMany()
                        .HasForeignKey("DefinitionGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefinitionGroup");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.DinnerTable", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.StatusOfDinnerTable", "StatusOfDinnerTable")
                        .WithMany()
                        .HasForeignKey("StatusOfDinnerTableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StatusOfDinnerTable");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Material", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.MaterialsGroup", "MaterialsGroup")
                        .WithMany()
                        .HasForeignKey("MaterialsGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.MaterialsStatus", "MaterialsStatus")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilkTea.Domain.Entities.Orders.Unit", "UnitMax")
                        .WithMany()
                        .HasForeignKey("UnitID_Max")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MaterialsGroup");

                    b.Navigation("MaterialsStatus");

                    b.Navigation("Unit");

                    b.Navigation("UnitMax");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Menu", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.MenuGroup", "MenuGroup")
                        .WithMany()
                        .HasForeignKey("MenuGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Users.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuGroup");

                    b.Navigation("Status");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.MenuAndMaterial", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Menu");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.MenuGroup", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.MenuSize", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Order", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.DinnerTable", "DinnerTable")
                        .WithMany()
                        .HasForeignKey("DinnerTableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.PromotionOnTotalBill", "PromotionOnTotalBill")
                        .WithMany()
                        .HasForeignKey("PromotionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilkTea.Domain.Entities.Orders.StatusOfOrder", "StatusOfOrder")
                        .WithMany()
                        .HasForeignKey("StatusOfOrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DinnerTable");

                    b.Navigation("PromotionOnTotalBill");

                    b.Navigation("StatusOfOrder");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.OrdersDetail", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.KindOfHotpot", "KindOfHotpot1")
                        .WithMany()
                        .HasForeignKey("KindOfHotpot1ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilkTea.Domain.Entities.Orders.KindOfHotpot", "KindOfHotpot2")
                        .WithMany()
                        .HasForeignKey("KindOfHotpot2ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilkTea.Domain.Entities.Orders.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.Order", "Order")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.PriceList", "PriceList")
                        .WithMany()
                        .HasForeignKey("PriceListID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MilkTea.Domain.Entities.Orders.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KindOfHotpot1");

                    b.Navigation("KindOfHotpot2");

                    b.Navigation("Menu");

                    b.Navigation("Order");

                    b.Navigation("PriceList");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.PriceList", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.StatusOfPriceList", "StatusOfPriceList")
                        .WithMany()
                        .HasForeignKey("StatusOfPriceListID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("StatusOfPriceList");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.PriceListDetail", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.PriceList", "PriceList")
                        .WithMany()
                        .HasForeignKey("PriceListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("PriceList");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.PromotionOnTotalBill", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.StatusOfPromotion", "StatusOfPromotion")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StatusOfPromotion");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Warehouse", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Users.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.WarehouseRollback", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Orders.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Employee", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Users.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Users.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Position");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Permission", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.PermissionGroup", "PermissionGroup")
                        .WithMany()
                        .HasForeignKey("PermissionGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.PermissionDetail", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.PermissionGroup", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.PermissionGroupType", "PermissionGroupType")
                        .WithMany()
                        .HasForeignKey("PermissionGroupTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroupType");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Role", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.RoleDetail", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.PermissionDetail", "PermissionDetail")
                        .WithMany()
                        .HasForeignKey("PermissionDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Users.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionDetail");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("MilkTea.Domain.Entities.Users.User", "EmployeesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Users.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.UserAndPermissionDetail", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.PermissionDetail", "PermissionDetail")
                        .WithMany()
                        .HasForeignKey("PermissionDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.UserAndRole", b =>
                {
                    b.HasOne("MilkTea.Domain.Entities.Users.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTea.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("OrdersDetails");
                });

            modelBuilder.Entity("MilkTea.Domain.Entities.Users.Employee", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
